import "./globals.css";
import { Inter } from "next/font/google";
import { Nav } from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col sm:flex-row h-screen overflow-hidden">
          <aside className="h-screen w-full sm:w-60">
            <Nav />
          </aside>
          <main className="h-screen flex-grow p-6 bg-blue-100 overflow-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
